### ISSUE TITLE
Conversion from mgf to mzML format

### ISSUE THREAD

**Issue by RobAlbn** [lehtiolab/nf-msconvert#1]
Is it possible to convert mgf files to mzML format by using MSConvert? If it is possible, is it necessary to select specific options in the Filters section, depending on specific data characteristics, such as the data type (DIA or DDA data) or the specific mass spectrometer that was used? Thank you!

Best regards, 
Roberto

**Comment by glormph** [comment]
Hello, this is merely a workflow for easy execution (in our lab) of raw -> mzML, so I'm not sure if it's possible, although MGF is a supported format by msconvert (see for more information also on filters to use etc: https://proteowizard.sourceforge.io/tools/msconvert.html).

Since this workflow is a wrapper around the docker msconvert container, it could either work, or you'd have to use e.g. the official docker container which is https://github.com/proteowizard/container. If there's some small adaptations that need to be done we can add those to this workflow if needed.

**Comment by RobAlbn** [comment]
Thank you very much for your answer!
